package ss15_exception.controller;

public class ExceptionStudy {
    public static void main(String[] args) {

        double n = 10.0/0 * 10.0/0;

        System.out.println("Giá trị của n: " + n);

        System.out.println("Chương trình kết thúc không lỗi lầm");
    }
}
